### ISSUE TITLE
Unexpected token export

### ISSUE THREAD

**Issue by jerold-tolentino** [ibrasho/pulumi-github#1]
error: Running program 'F:\SideProject\data-pipeline-jobs\github-testing' failed with an unhandled exception:
    F:\SideProject\data-pipeline-jobs\github-testing\node_modules\@ibrasho\pulumi-github\index.ts:5
    export * from "./branchProtection";
    ^^^^^^

    SyntaxError: Unexpected token export
        at Module._compile (internal/modules/cjs/loader.js:721:23)
        at Module._extensions..js (internal/modules/cjs/loader.js:787:10)
        at Object.require.extensions.(anonymous function) [as .ts] (F:\SideProject\data-pipeline-jobs\github-testing\node_modules\ts-node\src\index.ts:529:44)
        at Module.load (internal/modules/cjs/loader.js:653:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
        at Function.Module._load (internal/modules/cjs/loader.js:585:3)
        at Module.require (internal/modules/cjs/loader.js:690:17)
        at require (internal/modules/cjs/helpers.js:25:18)
        at Object.<anonymous> (F:\SideProject\data-pipeline-jobs\github-testing\index.ts:2:1)
        at Module._compile (internal/modules/cjs/loader.js:776:30)

How can I fix this issue?

**Comment by chapmanjacobd** [comment]
The author of this provider didn't publish it on npm in the correct location. But this isn't too bad. You can still use it like this:

```ts
import * as gh from '@ibrasho/pulumi-github/bin';
```

but you will need to get the provider plugin binary. the author here does not appear to have published that anywhere - so you will need to clone the repo and build it yourself (with Go).  Then put the resulting pulumi-provider-github binary on your PATH and things should work.
